In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
X.shape

(442, 10)

In [6]:
y.shape

(442,)

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
X_train.shape

(353, 10)

# Beta = (X.Transpose X)inverse dot X.Transpose dot Y

In [9]:
class my_LR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,Y_train):

        X_train = np.insert(X_train,0,1,axis=1)
        
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(Y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]


    def predict(self,X_test):

        y_pred = np.dot(X_test, self.coef_) + self.intercept_

        return y_pred

In [10]:
lr = my_LR()

In [11]:
lr.fit(X_train,Y_train)

In [12]:
y_pred = lr.predict(X_test)

In [13]:
Y_test.shape

(89,)

In [14]:
y_pred.shape

(89,)

In [15]:
from sklearn.metrics import r2_score

r2_score(y_pred,Y_test)

-0.015299458907067631

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
linear = LinearRegression()

In [18]:
linear.fit(X_train,Y_train)

LinearRegression()

In [19]:
new_pred = linear.predict(X_test)

In [20]:
r2_score(new_pred, Y_test)

-0.015299458907064079

In [21]:
linear.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [22]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [23]:
linear.intercept_

151.88331005254167

In [24]:
lr.intercept_

151.88331005254167